### ISSUE TITLE
20200810

### ISSUE THREAD

**Issue by kimhodol** [woowacourse-teams/2020-zeze#111]
## 20200810 

- [인프라 관련 저장소](https://github.com/minguinho/zeze-infra) 참고

### TODO

- 필수 요구사항
  - [x] https, ws, 도메인
  - [x] No DB Drop (@jjj0611, ~20200811)
    - [x] Flyway
  - [x] API 문서화 (@lowoon, ~20200810)
    - [x] 테스트 환경 properties 분리 (@lowoon)
  - [x] **현재까지 발표하지 않은 핀(@lalize)이 발표를 준비**
- Demo 
  - 인프라 (@jjj0611, ~20200810)
    - [x] Github action에서 `./gradlew clientBuild` -> S3 옮기는 작업
    - [x] zeze ec2
  - Admin (@kimhodol, ~20200810)
    - [x] S3에 `curl`해서 `.jar`, `static` 폴더 가져와서 적정 경로에 넣고 `run.sh` 실행시키기 (해당하는 Route 작성)
  - Product (@lalize, @kimhodol, ~20200810)
    - [x] 그냥 존나 느려
    - [x] 코드블록이나 페이지별로 Split을 해서 해볼까?
    - [x] 코드미러 이슈
  - Auth (@YerinCho, ~20200810)
    - [x] 로그인 
    - [x] 사용자 정보 연동 + API 통신
