### ISSUE TITLE
Final fix before v1

### ISSUE THREAD

**Issue by kimhodol** [woowacourse-teams/2020-zeze#197]
### Todo

- [x] 저희 저장이랑 자물쇠 표시 cursor: pointer가 없네요
- [x] pointer 안보이면 링크 못 누름
- [x] 링크 누르면 새 창에서 띄우기
- [x] 사이드바 `...` 가리기 @kimhodol 
- [x] 슬라이드 목록 아무것도 없을 때 슬라이드 추가 버튼 혹은 아무 것도 없다는 안내 메시지 추가 @lalize @YerinCho 
- [x] token 인증 안될 때 로그인 페이지로 보내기 @YerinCho 
- [x] 404 페이지 만들기 @kimhodol 
- [x] Public Slide 읽지 못하는 이슈 @lowoon 
  - [x] 다른 사람 페이지 들어갔을 때 경고 메세지 없이 저장, private만 버튼 없애기 @jjj0611 
- [x] private 토글과 저장 버튼 메세지 다르게 하기 @jjj0611 
- [x] 전반적인 모바일 대응 문제 @kimhodol 
- [x] 고객센터 / ~~회원 탈퇴~~ (Github Issue로 보내는 것도 좋은 생각. README에 홍보나 팀 소개 글 넣으면 좋을 듯) @kimhodol 

### 이거 해야함

- [ ] Sample PPT 만들기 (각 1개 이상, Public)
