### ISSUE TITLE
20200730 중간발표 대비

### ISSUE THREAD

**Issue by kimhodol** [woowacourse-teams/2020-zeze#82]
### To-do

- [x] 도메인 ([가비아](https://.gabia.com))
- [x] HTTPS (Let's Encrypt - [Certbot](https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx))
- [ ] Deploy
  - [ ] Jenkins
  - [ ] Github Action + S3 + Deploy server
  - [ ] Docker?
- [ ] Logger
  - [ ] Nginx (내장)
  - [ ] API Server Request
    - [ ] Controller specific
    - [ ] Error
  - [ ] MySQL (내장)
- [ ] 발표
